name: Test RSS diff to Twitter

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch RSS files
      run: |
        wget -O new.xml https://utelecon.adm.u-tokyo.ac.jp/notice/rss.xml

    - name: Run RSS diff to Twitter action
      uses: ./
      with:
        OLD_RSS: new.xml
        NEW_RSS: new.xml
        TWITTER_APIKEY: FOOBAR
        TWITTER_APIKEY_SECRET: FOOBAR
        TWITTER_ACCESS_TOKEN: FOOBAR
        TWITTER_ACCESS_TOKEN_SECRET: FOOBAR
